#pragma once
#include "Define.h"


Native("??$AddUniqueImpl@AEBVFString@@@?$TArray@VFString@@V?$TSizedDefaultAllocator@$0CA@@@@@AEAAHAEBVFString@@@Z", int, TArrayFString_AddUniqueImpl, void* self, const struct FString& str)
Native("??$CreateStatic@$$V@?$TBaseDelegate@U?$TTypeWrapper@X@@AEAUFVectorVMContext@@@@SA?AV?$TBaseDelegate@XAEAUFVectorVMContext@@@@P6AXAEAUFVectorVMContext@@@Z@Z", void, TBaseDelegate_CreateStatic, void* self, void* cb)
Native("??0FName@@QEAA@PEB_WW4EFindName@@@Z", void, FName_FName, struct FName* self, const wchar_t* str, enum EFindName e)
Native("??1?$TSharedRef@V?$TLocalizedTextData@VFTextHistory_AsDate@@@@$00@@QEAA@XZ", void*, FText_Destructor, void* self)
Native("?ApplyCVarSettingsFromIni@@YAXPEB_W0I_N@Z", void, ApplyCVarSettingsFromIni, const wchar_t* InSectionName, const wchar_t* InIniFilename, enum EConsoleVariableFlags SetBy, bool bAllowCheating)
Native("?CallAllConsoleVariableSinks@FConsoleManager@@UEAAXXZ", void, FConsoleManager_CallAllConsoleVariableSinks, void* self)
Native("?ClientAddAnnouncementMessage@UMistPlayerMessengerComponent@@QEAAXAEBVFText@@@Z", void, UMistPlayerMessengerComponent_ClientAddAnnouncementMessage, struct UMistPlayerMessengerComponent* self, const struct FText& text)
Native("?ClientAddChallenger@UMistDuellingInteractableComponent@@AEAAXPEAVAMistPlayer@@H@Z", void, UMistDuellingInteractableComponent_ClientAddChallenger, void* self, struct AMistPlayer* player, int a);
Native("?ClientAddHudCountdown@AMistOasisPlayerController@@QEAAXAEBVFString@@AEBUFMistHudCountdownOptions@@@Z", void, AMistOasisPlayerController_ClientAddHudCountdown, struct AMistOasisPlayerController* self, const struct FString& str, const struct FMistHudCountdownOptions& opt)
Native("?ClientAddHudLog@AMistOasisPlayerController@@QEAAXAEBVFName@@AEBVFText@@@Z", void, AMistOasisPlayerController_ClientAddHudLog, struct AMistOasisPlayerController* self, const FName& name, const struct FText& text)
Native("?ClientAddHudMessage@AMistOasisPlayerController@@QEAAXAEBUFMistHudMessageOptions@@@Z", void, AMistOasisPlayerController_ClientAddHudMessage, struct AMistOasisPlayerController* self, const struct FMistHudMessageOptions& opt)
Native("?ClientAddInformationMessage@UMistPlayerMessengerComponent@@QEAAXAEBVFText@@@Z", void, UMistPlayerMessengerComponent_ClientAddInformationMessage, struct UMistPlayerMessengerComponent* self, const struct FText& text)
Native("?ClientAddNotificationChatMessage@UMistPlayerMessengerComponent@@QEAAXAEBW4EPlayerCharacterNotificationType@@AEBVFText@@@Z", void, UMistPlayerMessengerComponent_ClientAddNotificationChatMessage, struct UMistPlayerMessengerComponent* self, const char& type, const struct FText& text)
Native("?Free@FMemory@@SAXPEAX@Z", void, FMemory_Free, void* p)
Native("?FromString@FText@@SA?AV1@$$QEAVFString@@@Z", void*, FText_FromStringR, struct FText* self, struct FString&& str)
Native("?FromString@FText@@SA?AV1@AEBVFString@@@Z", void*, FText_FromStringC, struct FText* self, const struct FString& str)
Native("?Get@FWeakObjectPtr@@QEBAPEAVUObject@@XZ", void*, FWeakObjectPtr_Get, void* self)
Native("?Get@UOnlineHotfixManager@@SAPEAV1@PEAVUWorld@@@Z", void*, UOnlineHotfixManager_Get, struct UWorld* world)
Native("?GetActorCount@UWorld@@QEAAHXZ", int, UWorld_GetActorCount, struct UWorld* self)
Native("?GetComponentByClass@AActor@@QEBAPEAVUActorComponent@@V?$TSubclassOf@VUActorComponent@@@@@Z", struct UActorComponent*, AActor_GetComponentByClass, struct AActor* self, struct UClass* cls)
Native("?GetContent@FCurlHttpRequest@@UEBAAEBV?$TArray@EV?$TSizedDefaultAllocator@$0CA@@@@@XZ", void*, FCurlHttpRequest_GetContent, void* self)
Native("?GetContent@FCurlHttpResponse@@UEBAAEBV?$TArray@EV?$TSizedDefaultAllocator@$0CA@@@@@XZ", void*, FCurlHttpResponse_GetContent, void* self)
Native("?GetContentLength@FCurlHttpRequest@@UEBAHXZ", int, FCurlHttpRequest_GetContentLength, void* self)
Native("?GetContentLength@FCurlHttpResponse@@UEBAHXZ", int, FCurlHttpResponse_GetContentLength, void* self)
Native("?GetContentType@FCurlHttpRequest@@UEBA?AVFString@@XZ", void*, FCurlHttpRequest_GetContentType, void* self, struct FString* type)
Native("?GetGameMode@AActor@@QEBAPEAVAGameModeBase@@XZ", struct AGameMode*, AActor_GetGameMode, struct AActor* self)
Native("?GetNumPlayers@AGameMode@@UEAAHXZ", int, AGameMode_GetNumPlayers, struct AGameMode* self)
Native("?GetPawnOrSpectator@APlayerController@@QEBAPEAVAPawn@@XZ", struct APawn*, APlayerController_GetPawnOrSpectator, struct APlayerController* self)
Native("?GetPlayerControllerIterator@UWorld@@QEBA?AV?$TIndexedContainerIterator@$$CBV?$TArray@U?$TWeakObjectPtr@VAPlayerController@@UFWeakObjectPtr@@@@V?$TSizedDefaultAllocator@$0CA@@@@@$$CBU?$TWeakObjectPtr@VAPlayerController@@UFWeakObjectPtr@@@@H@@XZ", void, UWorld_GetPlayerControllerIterator, struct UWorld* self, void* it)
Native("?GetPlayerState@APawn@@UEBAPEAVAPlayerState@@XZ", struct APlayerState*, APawn_GetPlayerState, struct APawn* self)
Native("?GetURL@FCurlHttpRequest@@UEBA?AVFString@@XZ", void*, FCurlHttpRequest_GetURL, void* self, struct FString* url)
Native("?GetURL@FCurlHttpResponse@@UEBA?AVFString@@XZ", void*, FCurlHttpResponse_GetURL, void* self, struct FString* url)
Native("?GetVerb@FCurlHttpRequest@@UEBA?AVFString@@XZ", void*, FCurlHttpRequest_GetVerb, void* self, struct FString* verb)
Native("?GetWorld@UObject@@UEBAPEAVUWorld@@XZ", struct UWorld*, UObject_GetWorld, struct UObject* self)
Native("?Logf_InternalImpl@FMsg@@CAXPEBDHAEBVFName@@W4Type@ELogVerbosity@@PEB_WZZ", void, Logf_InternalImpl, char* a0, int a1, struct FName* source, enum ELogVerbosity level, const wchar_t* format, ...)
Native("?Malloc@FMemory@@SAPEAX_KI@Z", void*, FMemory_Malloc, size_t count, unsigned int align)
Native("?PatchAssetsFromIniFiles@UOnlineHotfixManager@@MEAAXXZ", void, UOnlineHotfixManager_PatchAssetsFromIniFiles, void* self)
Native("?RegisterConsoleVariableRef@FConsoleManager@@UEAAPEAVIConsoleVariable@@PEB_WAEAH0I@Z", void*, FConsoleManager_RegisterConsoleVariableRef_Int, void* self, const wchar_t* cvar, int& var, const wchar_t* desc, enum EConsoleVariableFlags flags)
Native("?RegisterConsoleVariableRef@FConsoleManager@@UEAAPEAVIConsoleVariable@@PEB_WAEAM0I@Z", void*, FConsoleManager_RegisterConsoleVariableRef_Float, void* self, const wchar_t* cvar, float& var, const wchar_t* desc, enum EConsoleVariableFlags flags)
Native("?RegisterConsoleVariableRef@FConsoleManager@@UEAAPEAVIConsoleVariable@@PEB_WAEAVFString@@0I@Z", void*, FConsoleManager_RegisterConsoleVariableRef_FString, void* self, const wchar_t* cvar, struct FHeapString& var, const wchar_t* desc, enum EConsoleVariableFlags flags)
Native("?ServerMapChat@UMistPlayerMessengerComponent@@QEAAXAEBVFString@@@Z", void, UMistPlayerMessengerComponent_ServerMapChat, struct UMistPlayerMessengerComponent* self, const struct FString& text)
Native("?SetOnChangedCallback@FConsoleVariableBase@@UEAAXAEBV?$TBaseDelegate@XPEAVIConsoleVariable@@@@@Z", void*, FConsoleVariableBase_SetOnChangedCallback, void* self, const struct FConsoleVariableDelegate& dg)
Native("?ToString@FName@@QEBA?AVFString@@XZ", void*, FName_ToString, struct FName* self, void* str)

Native("?UtcTime@FWindowsPlatformTime@@SAXAEAH0000000@Z", void, FWindowsPlatformTime_UtcTime, int* year, int* month, int* dayOfWeek, int* day, int* hour, int* minutes, int* seconds, int* milliseconds)
Native("?GetOwnershipComponent@FMistClanUtils@@SAPEAVUMistClanOwnershipComponent@@PEAVAActor@@_N@Z", struct UMistClanOwnershipComponent*, FMistClanUtils_GetOwnershipComponent, struct AActor* self, bool value)
Native("??$GetPlayerState@VAMistOasisPlayerState@@@APawn@@QEBAPEAVAMistOasisPlayerState@@XZ", struct AMistOasisPlayerState*, APawn_GetPlayerStateMist, struct APawn* self)
Native("??$GetPawn@VAMistPlayer@@@AController@@QEBAPEAVAMistPlayer@@XZ", struct AMistPlayer*, AController_GetPawnPlayer, struct AController* self)
Native("?KickPlayer@AMistPlayerController@@QEAAXAEBVFText@@@Z", void, AMistPlayerController_KickPlayer, struct AMistPlayerController* self, const struct FText& reason)
Native("?GetWalker@AMistPlayer@@UEBAPEAVAMistWalker@@XZ", struct AMistWalker*, AMistPlayer_GetWalker, struct AMistPlayer* self)
Native("?IsManningWalker@AMistPlayer@@QEAA_NXZ", bool, AMistPlayer_IsManningWalker, struct AMistPlayer* self)
Native("?SetCustomName@AMistWalker@@QEAAXAEBVFString@@@Z", void, AMistWalker_SetCustomName, struct AMistWalker* self, const struct FString* namePtr)
Native("??$GetGameMode@VAMistOasisGameMode@@@AActor@@QEBAPEAVAMistOasisGameMode@@XZ", struct AMistOasisGameMode*, AActor_GetMistGameMode, struct AActor* self)
Native("?StartShutdown@AMistOasisGameMode@@QEAAX_N@Z", void, AMistOasisGameMode_StartShutdown, struct AMistOasisGameMode* self, bool value)
Native("?GetTotalWater@AMistWalker@@QEAAHXZ", int64, AMistWalker_GetTotalWater, struct AMistWalker* self)
Native("?GetMaximumWater@AMistWalker@@QEAAHXZ", int64, AMistWalker_GetMaximumWater, struct AMistWalker* self)
Native("?GetCurrentSpeed@AMistWalker@@QEBAMXZ", float, AMistWalker_GetCurrentSpeed, struct AMistWalker* self)
Native("??$GetController@VAMistOasisPlayerController@@@APawn@@QEBAPEAVAMistOasisPlayerController@@XZ", struct AMistOasisPlayerController*, APawn_GetControllerMist, struct APawn* self)